image: debian:unstable

stages:
    - build
    - test
    - deploy

build_job:
  stage: build
  except: 
    - fs-pages
  script:
    - cmake .
    - make

test_job:
  stage: test
  except: 
    - fs-pages
  script:
  - export DISPLAY=:1
  - cmake .
  - make
  - ./ae-test
